version: '3'
networks:
      backend:
services:
      mysql_db:
            container_name: 'mysql-db'
            image: mysql:latest
            restart: 'always'
            command: --default-authentication-plugin=mysql_native_password
            environment:
                  MYSQL_DATABASE: 'bitespeed'
                  # So you don't have to use root, but you can if you like
                  MYSQL_USER: 'user'
                  # You can use whatever password you like
                  MYSQL_PASSWORD: 'password'
                  # Password for root access
                  MYSQL_ROOT_PASSWORD: 'password'
                  MYSQL_ROOT_HOST: '%'
            ports:
                  - '3307:3306'
            expose:
                  - '3307'
            volumes:
                  - my-db:/var/lib/mysql
            networks:
                  - backend
      node-api:
            container_name: 'nodeJS-app'
            build: .
            ports:
                  - 3001:3001
            depends_on:
                  - mysql_db
            networks:
                  - backend
            command: sh -c 'sleep 5; node bin/index.js'
volumes:
      my-db: {}